export const ACTIONS = {
    PROPERTIES: {
        GET_PROPERTIES_REQUEST: 'ACTIONS.PROPERTIES.GET_PROPERTIES_REQUEST',
        GET_PROPERTIES_SUCCESS: 'ACTIONS.PROPERTIES.GET_PROPERTIES_SUCCESS',
        GET_PROPERTIES_FAILURE: 'ACTIONS.PROPERTIES.GET_PROPERTIES_FAILURE',
    },
};
